// TODO: Refactor into a JSON file, if needed.
var EQUATIONS = [
    ['1', 'Fraction 1', 'x=\\frac{11+y}{1+2z^2}'],
    ['2', 'Fraction 2', 'x=\\frac{1+y}{1+2z^2}'],
    ['3', 'Fraction 3', 'x=\\frac{1+y}{1+2x^2}'],
    ['4', 'Big fraction', '2 = \\left( \\frac{\\left(3-x\\right) \\times 2}{3-x} \\right)'],
    ['5', 'Square', 'x={-b\\pm\\sqrt{b^2-4ac} \\over 2a}'],
    ['6', 'Integration', '\\int_\\zero^\\infty e^{-x^2} dx=\\frac{\\sqrt{\\pi}}{2}'],
    ['7', 'Superscript and subscript', 'x = 10^{20}_5'],
    ['8', 'Sum', '\\sum_{n=1}^\\infty {1\\over n^2} = {\\pi^2\\over 6}'],
    ['9', 'Lightspeed', '\\lspeed = 299792458{m \\over \\scnd}'],
    ['10', 'Initial charge', 'q = 10'],
    ['11', 'Energy', 'E = x'],
    ['12', 'Meter', 'x = 10m + 20\\cm'],
    ['13', 'Misc symbols A', 'a = \\epsilonzero + \\varepsilon'],
    ['14', 'Misc symbols B', 'b = \\phi + \\lambda + \\theta + \\Phi'],
    ['15', 'Misc symbols C', 'c = \\eta + €'],
    ['16', 'Plancks and Boltzmanns', '\\Plancks \\neq \\Boltzmanns'],
    ['17', 'Air Mass', '\\AM = x'],
    ['18', 'Radiation', '\\rad = x'],
    ['19', 'Amplifiers', '1\\Mega, 2\\nano, 3\\Giga, 4\\Tera, 3\\kilo, 20\\micro'],
    ['20', 'Electricity', '\\Watt = \\Amp \\times \\volt'],
    ['21', 'Sine and Cosine', '\\tan \\theta = {\\cos \\theta \\over \\sin \\theta}'],
    ['22', 'Temrature', '\\Tmpr = 10\\Klvn'],
    ['23', 'Current', '\\current = 10\\Amp'],
    ['24', 'ER #1', '\\er'],
    ['24.b', 'ER #2', '\\er = x'],
    ['25', 'The J stuff', '\\J_\\zero, \\J_\\ph, \\J_\\diffe, \\J_\\sc'],
    ['26', 'Voltage of Open Circuit', '\\V_\\oc'],
    ['27', 'Concentation Stuff', '\\NA, \\ND, \\nii'],
    ['28', 'Deplation Area', '\\Wd = x'],
    ['29', 'Farad', '\\F = {{\\scnd^4 \\cdot \\Amp^2} \\over {\\kilo\\grm \\cdot m^2}}'],
    ['30', 'Diffusion Length', '\\Ld = 10m'],
    ['31', 'Electrons Diffusion', '\\D_\\ek'],
    ['32', 'Electrons Motion Constant', '\\mue'],
    ['33', 'Hole', '20\\hole'],
    ['34', 'Electrons', '2 \\elctrn'],
    ['35', 'Time', '1\\year = 365.25\\day, 1\\day = 24\\hour'],
    ['36', 'Max Watt', '\\Watt_\\max'],
    ['37', 'Fill Factor', '\\FF'],
    ['38', 'Photovoltaic Energy', '\\P_\\inn'],
    ['39', 'Limits', 'e^x=\\lim_{n\\to\\infty} \\left( 1+\\frac{x}{n} \\right)^n'],
    ['40', 'Limits #2', 'e^x=\\lim_{4578545n\\to\\infty} y'],
    ['41', 'F prime of x', 'y = f^\\prime(x)'],
    ['42', 'F double prime of x', 'y = f^{\\prime\\prime}(x)'],
    ['43', 'F triple prime of x', 'y = f^{\\prime\\prime\\prime}(x)'],
    ['44', 'Matrix', '\\left[ \\begin{array}{rr} 5 & -2 \\\\ 3 & \\zero \\end{array} \\right]'],
    ['45', 'Matrix #2', '\\left[ \\begin{array}{rr} 1 & 4 \\\\ 10 & 7 \\end{array} \\right]'],
    ['46', 'Matrix #3', '\\left[ \\begin{array}{rr} 5 & -2 & 5 \\\\ 5 && -2 \\\\ 3 & \\zero & 10 \\end{array} \\right]'],
    ['47', 'Piecewise (Branched) function #1', 'x = \\left\\{\\begin{array}{l} a + b = 0\\\\ \\varphi a + \\psi b = 1\\end{array}\\right.'],
    ['48', 'Log', '\\log_b(xy) = \\log_b (x) + \\log_b (y), \\,'],
    ['49', 'Union and Intersection', 'A \\cup B \\cap C'],
    ['50', 'Some signs', 'A \\ne B \\leq C \\not\\subset \\Delta'],
    ['51', 'More vars', 'l \\neq m'],
    ['52', 'Area and Radius', '\\Area = \\pi\\radius^2'],
    ['54', 'Stretchy Arrow', '\\xrightarrow{\\Delta A + \\radius^{20}}\\ =\\ \\xrightarrow{B}'],
    ['55', 'Function composition', '(g \\circ h)(x) = h(g(x))'],
    ['66', 'Piecewise Function #2', 'f(x) = \\left\\{\\begin{array}{l} \\left[ {1 \\over 2}x + 2 \\right]  \\ , 2 \\le x \\lt 4 \\\\ { \\left| 4x \\right| \\over x^2-36 } \\ , x \\ge 4 \\end{array}\\right.'],
    ['67', 'Piecewise Function #3', 'f(x) = \\left\\{ \\begin{array}{l} ax^2 - bx \\ , x \\lt 3 \\\\ a x^3+6bx-9 \\ , x\\ge3 \\end{array}\\right.'],
    ['68', 'Piecewise function #4 (Arabic)', 'x = \\left\\{\\begin{array}{l} abc + 10 \\\\ xyz + 20 \\end{array}\\right.'],
    ['70', 'Polynomial', 'f(x) = ax^3+6bx-9'],
    ['71', 'Array (Table)', 'q(x) = \\begin{array}{l} 1y & {z \\over a - 2} \\\\ be^3  & {c \\over g - 4} \\end{array}'],
    ['72', 'Bare bones array', '\\begin{array}{l} 5 \\\\ h^6 \\end{array}'],
    ['73', 'Cases (Piecewise) Environment', '|x| = \\begin{cases} x  & \\transt{\\text{ if }}{ إذا } x \\ge 0 \\\\ -x & \\transt{\\text{ if }}{ إذا } x \\lt 0 \\end{cases}'],
    ['74', 'Parenthesis Matrix', '\\begin{pmatrix} aaa & b\\cr c   & ddd \\end{pmatrix}'],
    ['78', 'More Math Functions', '\\cot x , \\sec y , \\csc z '],
    ['79', 'Single Square Root', '\\sqrt{2}'],
    ['80', 'Semi colon', 'x=y; y=0'],
    ['81', 'Single right arrow', 'a \\rightarrow b'],
    ['82', 'Factorial', 'n!'],
].map(function (el) {
    return {
        id: el[0],
        name: el[1],
        equation: el[2]
    };
}).reverse();
